### ISSUE TITLE
problem in generating result.jpg: filter doesn't work well

### ISSUE THREAD

**Issue by ghost** [VladKarpushin/Periodic-noise-removing-filter#1]
Maybe a problem with opencv, but for now I cannot specify it as the example has the same error on a Win10 machine and also on Linux (Ubuntu 18.04). Any ideas? P.S. The first picture is my "result.jpg" not the input.

![result](https://user-images.githubusercontent.com/5595271/98447135-c7d28780-2122-11eb-9d04-5eafa2bd0f3b.jpg)
![filter](https://user-images.githubusercontent.com/5595271/98447136-c903b480-2122-11eb-8e9f-74e3a8abd86a.jpg)
![PSD](https://user-images.githubusercontent.com/5595271/98447137-c99c4b00-2122-11eb-8995-074d56c2b81e.jpg)

**Comment by VladKarpushin** [comment]
![input](https://user-images.githubusercontent.com/40189112/98489961-a7a9e200-2262-11eb-8224-89ec4ab83463.jpg)
Dear Julian. Try to use the original input image. Attached.

**Comment by ghost** [comment]
Thank you. I used the wrong image. With the original image it works well.
